# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/rockchip/rk3576-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter rk3576,$(TARGET_BOARD_PLATFORM)),)

endif
