#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/rockchip/rk3576-common

PRODUCT_COPY_FILES += \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/aipq_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/aipq_config.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/bluetooth/bt_vendor.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/bt_vendor.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/bluetooth/rtkbt.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/rtkbt.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/bluetooth/skwbt.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/skwbt.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/bluetooth/sv6160.nvbin:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/sv6160.nvbin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/bluetooth/sv6316.nvbin:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/sv6316.nvbin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/README.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/README.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk1126.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk1126.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3126c.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3126c.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3288.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3288.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3326.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3326.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3368.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3368.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3399.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3399.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3399_1608.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3399_1608.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3399pro.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3399pro.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3562.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3562.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk356x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk356x.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3576.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3576.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/camera3_profiles_rk3588.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera3_profiles_rk3588.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/graph_descriptor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/graph_descriptor.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ar0144_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ar0144_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/bg0806_86mc09-l09_trc-2177d6-01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/bg0806_86mc09-l09_trc-2177d6-01.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc0403_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc0403_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc2023_pc0qq0004b_hk-8277g.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc2023_pc0qq0004b_hk-8277g.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc2053_pc0rd0003a_2121f6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc2053_pc0rd0003a_2121f6.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc2355_CMK-CW2392_M206A-201.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc2355_CMK-CW2392_M206A-201.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc2375_hs752af-s20-v02_tr213-h02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc2375_hs752af-s20-v02_tr213-h02.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc2385_CMK-CL4154-FG3_TL0534-2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc2385_CMK-CL4154-FG3_TL0534-2.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc2385_cmk-ot1226-fg1_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc2385_cmk-ot1226-fg1_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc2385_pcg301139-a0_m286.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc2385_pcg301139-a0_m286.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc5025_CMK-CW4191-FG1_CK5502.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc5025_CMK-CW4191-FG1_CK5502.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc5025_hs5025b-s20-v01_1439ags.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc5025_hs5025b-s20-v01_1439ags.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc5025_m75qf6g45g25_xhj501-65.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc5025_m75qf6g45g25_xhj501-65.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc5035_cq95-hl106f-5035-v1_htt-m503b-70.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc5035_cq95-hl106f-5035-v1_htt-m503b-70.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc5035_gs5355a-vcm2_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc5035_gs5355a-vcm2_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc8034_CMK-CT1841-FK3_CK8401.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc8034_CMK-CT1841-FK3_CK8401.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc8034_LH-RK-8034-v1.0_CK8401.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc8034_LH-RK-8034-v1.0_CK8401.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/gc8034_cq95-hl106b-8034-v1_dsc-0843.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/gc8034_cq95-hl106b-8034-v1_dsc-0843.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/hi846_st-f8f801_gs-8938aa.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/hi846_st-f8f801_gs-8938aa.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/imx258_GEIR180089_LG500627G.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/imx258_GEIR180089_LG500627G.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/imx317-preisp_HJM5040A31700A_HJM5040A31700A.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/imx317-preisp_HJM5040A31700A_HJM5040A31700A.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/imx327-preisp_SIDB02300229-VA_2G4P-IR.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/imx327-preisp_SIDB02300229-VA_2G4P-IR.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/imx327_TongJu_CHT842-MD.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/imx327_TongJu_CHT842-MD.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/imx327_cmk-ot0838-pt2_yt-2929-14-650-h30x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/imx327_cmk-ot0838-pt2_yt-2929-14-650-h30x.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/jx_h62_taichuan_cateye.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/jx_h62_taichuan_cateye.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/jx_h65_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/jx_h65_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/jx_h65_ledong_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/jx_h65_ledong_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov13850_CMK-CT0116_Largan-50013A1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov13850_CMK-CT0116_Largan-50013A1.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov13850_cmk-ot1227-fv1_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov13850_cmk-ot1227-fv1_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov2680_KYT-3359-V5.0_M216A-233.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov2680_KYT-3359-V5.0_M216A-233.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov2680_SY1927-R863-0A19-2680-V1_TR213-H07.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov2680_SY1927-R863-0A19-2680-V1_TR213-H07.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov2680_cy2680mf3055_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov2680_cy2680mf3055_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov2685_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov2685_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov2710_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov2710_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov2718-preisp_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov2718-preisp_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov2718_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov2718_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov2718_ov20-jm01-d0_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov2718_ov20-jm01-d0_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov2735_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov2735_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov4689_JSD3425-C1_JSD3425-C1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov4689_JSD3425-C1_JSD3425-C1.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov5648_bxf-1c9g10av1_m5182.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov5648_bxf-1c9g10av1_m5182.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov5648_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov5648_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov5648_kyt-2125-b-v3_t5gs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov5648_kyt-2125-b-v3_t5gs.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov5648_st94-zk636-v1_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov5648_st94-zk636-v1_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov5695_TongJu_CHT842-MD.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov5695_TongJu_CHT842-MD.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov5695_avl-rk-lh-5m-1-v1_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov5695_avl-rk-lh-5m-1-v1_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov7221_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov7221_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov7251_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov7251_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov7750_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov7750_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov8858_CameraKing_Largan-9569A2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov8858_CameraKing_Largan-9569A2.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov8858_hs5845-xct6-v1_g4402a.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov8858_hs5845-xct6-v1_g4402a.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov9281_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov9281_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/ov9282_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/ov9282_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/s5k4h8_bcf-h800-b05c-v03_13505a08.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/s5k4h8_bcf-h800-b05c-v03_13505a08.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/s5k4h8_hm618b-4h8-v1_s5ae08.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/s5k4h8_hm618b-4h8-v1_s5ae08.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/sc031gs_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/sc031gs_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/sc132gs_blackvision_f00101a.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/sc132gs_blackvision_f00101a.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp1/sc2232_default_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp1/sc2232_default_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/CAC_sc4336_OT01_40IRC_F16/cac_map_hw_1920x1080.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/CAC_sc4336_OT01_40IRC_F16/cac_map_hw_1920x1080.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/CAC_sc4336_OT01_40IRC_F16/cac_map_hw_2560x1440.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/CAC_sc4336_OT01_40IRC_F16/cac_map_hw_2560x1440.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/OX03C10.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/OX03C10.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/gc05a2_KYT-11210-V2_default.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/gc05a2_KYT-11210-V2_default.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/imx415_CMK-OT2022-PX1_IR0147-50IRC-8M-F20.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/imx415_CMK-OT2022-PX1_IR0147-50IRC-8M-F20.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/imx464_CMK-OT1980-PX1_SHG102.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/imx464_CMK-OT1980-PX1_SHG102.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/os04a10_CMK-OT1607-FV1_M12-40IRC-4MP-F16.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/os04a10_CMK-OT1607-FV1_M12-40IRC-4MP-F16.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/ov16880_KYT-11379-V1_default.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/ov16880_KYT-11379-V1_default.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/s5k3l8xx_KYT-11097-B-V1_default.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/s5k3l8xx_KYT-11097-B-V1_default.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/s5k4h5yb_G1-T-B-s5k_XA-0806B.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/s5k4h5yb_G1-T-B-s5k_XA-0806B.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/camera/rkisp2/sc4336_OT01_40IRC_F16.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/rkisp2/sc4336_OT01_40IRC_F16.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/cfg_rockchip_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_rockchip_default.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/external_camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/external_camera_config.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/4343A0.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/4343A0.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/4359_cypress_auto.clm_blob:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/4359_cypress_auto.clm_blob \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/AP6275P_NVRAM_V1.1_20200702.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/AP6275P_NVRAM_V1.1_20200702.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM20710A1.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM20710A1.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4330B1.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4330B1.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4343A0.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4343A0.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4343A1.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4343A1.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4343B0.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4343B0.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4345C0.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4345C0.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4345C5.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4345C5.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4354A2.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4354A2.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4356A2.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4356A2.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4359C0-CYW.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4359C0-CYW.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4359C0.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4359C0.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/BCM4362A2.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/BCM4362A2.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/EA6521QF_SEEKWAVE_R00005.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/EA6521QF_SEEKWAVE_R00005.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/EA6521QF_SEEKWAVE_R00005.ini:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/EA6521QF_SEEKWAVE_R00005.ini \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/EA6521QT_SEEKWAVE_R00005.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/EA6521QT_SEEKWAVE_R00005.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/EA6521QT_SEEKWAVE_R00005.ini:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/EA6521QT_SEEKWAVE_R00005.ini \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/EA6621QT_SEEKWAVE_R00005.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/EA6621QT_SEEKWAVE_R00005.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/EA6621QT_SEEKWAVE_R00005.ini:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/EA6621QT_SEEKWAVE_R00005.ini \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/EA6621Q_SEEKWAVE_R00005.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/EA6621Q_SEEKWAVE_R00005.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/EA6621Q_SEEKWAVE_R00005.ini:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/EA6621Q_SEEKWAVE_R00005.ini \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/RAM_RW_KERNEL_DRAM.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/RAM_RW_KERNEL_DRAM.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/ROM_EXEC_KERNEL_IRAM.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ROM_EXEC_KERNEL_IRAM.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/RT2870AP.dat:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/RT2870AP.dat \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/RT2870APCard.dat:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/RT2870APCard.dat \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/RT2870STA.dat:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/RT2870STA.dat \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/RT2870STACard.dat:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/RT2870STACard.dat \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/TV_Firmware.mk:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/TV_Firmware.mk \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/aic_userconfig.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/aic_userconfig.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/aic_userconfig_8800d80.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/aic_userconfig_8800d80.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/aic_userconfig_8800dc.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/aic_userconfig_8800dc.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/aic_userconfig_8800dw.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/aic_userconfig_8800dw.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/awnb108.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/awnb108.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm20710a1.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm20710a1.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm20710a1_24M.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm20710a1_24M.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm20710a1_26M.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm20710a1_26M.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm2076b1.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm2076b1.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm40183b2.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm40183b2.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm43241b4.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm43241b4.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm4329.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm4329.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm43341b0.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm43341b0.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm4339a0.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm4339a0.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm43438a0.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm43438a0.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm43438a1.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm43438a1.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/bcm4354a1.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bcm4354a1.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/chipone_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/chipone_firmware.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/clm_bcm4359c51a2_ag.blob:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/clm_bcm4359c51a2_ag.blob \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/clm_bcm43752a2_ag.blob:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/clm_bcm43752a2_ag.blob \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/clm_bcm43752a2_pcie_ag.blob:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/clm_bcm43752a2_pcie_ag.blob \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/clm_syn43711a0.blob:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/clm_syn43711a0.blob \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/clm_syn43756b0.blob:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/clm_syn43756b0.blob \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_8800d80.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_8800d80.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_8800d80_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_8800d80_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_8800m_custmsg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_8800m_custmsg.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_calib_8800dc_h_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_calib_8800dc_h_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_calib_8800dc_hbt_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_calib_8800dc_hbt_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_calib_8800dc_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_calib_8800dc_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_8800dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_8800dc.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_8800dc_h_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_8800dc_h_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_8800dc_hbt_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_8800dc_hbt_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_8800dc_ipc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_8800dc_ipc.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_8800dc_ipc_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_8800dc_ipc_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_8800dc_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_8800dc_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_tbl_8800dc_h_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_tbl_8800dc_h_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_tbl_8800dc_hbt_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_tbl_8800dc_hbt_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_tbl_8800dc_ipc_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_tbl_8800dc_ipc_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_patch_tbl_8800dc_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_patch_tbl_8800dc_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_rf.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_rf.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_rf_8800d80.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_rf_8800d80.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_rf_8800d80_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_rf_8800d80_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfw_rf_patch_8800dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfw_rf_patch_8800dc.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfwbt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfwbt.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fmacfwbt_8800d80_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fmacfwbt_8800d80_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK901.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK901.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK901a0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK901a0.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK901a0_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK901a0_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK901a2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK901a2.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK901a2_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK901a2_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK901a2_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK901a2_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK903.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK903.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK903_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK903_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK903_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK903_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK903_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK903_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK903_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK903_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK903b2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK903b2.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK903b2_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK903b2_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_RK903b2_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_RK903b2_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_adid.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_adid.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_adid_8800d80.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_adid_8800d80.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_adid_8800d80_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_adid_8800d80_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_adid_8800dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_adid_8800dc.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_adid_8800dc_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_adid_8800dc_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_adid_8800dc_u02h.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_adid_8800dc_u02h.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_adid_u03.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_adid_u03.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_awnb108.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_awnb108.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_awnb108_ap.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_awnb108_ap.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm40181a2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm40181a2.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm40181a2_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm40181a2_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm40183b2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm40183b2.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm40183b2_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm40183b2_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm40183b2_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm40183b2_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm40183b2_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm40183b2_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm40183b2_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm40183b2_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm40183b2_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm40183b2_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43241b4_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43241b4_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43241b4_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43241b4_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43241b4_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43241b4_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4330.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4330.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4330_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4330_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43341b0_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43341b0_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43341b0_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43341b0_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43341b0_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43341b0_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4334b1_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4334b1_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4334b1_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4334b1_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4334b1_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4334b1_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4339a0_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4339a0_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4339a0_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4339a0_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4339a0_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4339a0_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43436b0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43436b0.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43436b0_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43436b0_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43436b0_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43436b0_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43438a0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43438a0.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43438a0_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43438a0_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43438a0_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43438a0_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43438a1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43438a1.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43438a1_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43438a1_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43438a1_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43438a1_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43455c0_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43455c0_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43455c0_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43455c0_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43455c0_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43455c0_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43456c5_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43456c5_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43456c5_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43456c5_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4354a1_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4354a1_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4354a1_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4354a1_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4354a1_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4354a1_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4356a2_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4356a2_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4356a2_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4356a2_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4356a2_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4356a2_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4359c0_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4359c0_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4359c0_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4359c0_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4359c0_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4359c0_ag_p2p.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm4359c51a2_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm4359c51a2_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43752a2_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43752a2_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43752a2_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43752a2_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43752a2_pcie_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43752a2_pcie_ag.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm43752a2_pcie_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm43752a2_pcie_ag_apsta.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_bcm88459_pcie.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcm88459_pcie.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_cyw43438.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_cyw43438.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_cyw43455.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_cyw43455.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_info.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_info.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_8800d80.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_8800d80.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_8800d80_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_8800d80_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_8800dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_8800dc.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_8800dc_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_8800dc_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_8800dc_u02h.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_8800dc_u02h.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_table.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_table.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_table_8800d80.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_table_8800d80.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_table_8800d80_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_table_8800d80_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_table_8800dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_table_8800dc.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_table_8800dc_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_table_8800dc_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_table_8800dc_u02h.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_table_8800dc_u02h.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_table_u03.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_table_u03.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_test.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_test.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_patch_u03.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_patch_u03.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_syn43711a0_sdio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_syn43711a0_sdio.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/fw_syn43756b0_pcie.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_syn43756b0_pcie.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/lmacfw_rf_8800d80.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/lmacfw_rf_8800d80.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/lmacfw_rf_8800d80_u02.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/lmacfw_rf_8800d80_u02.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/lmacfw_rf_8800dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/lmacfw_rf_8800dc.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nh660.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nh660.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_4330.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_4330.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_4330_oob.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_4330_oob.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6181.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6181.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6210.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6210.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6210_24M.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6210_24M.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6234.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6234.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6275P.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6275P.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6330.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6330.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6335.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6335.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6441.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6441.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6476.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6476.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_AP6493.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_AP6493.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_B23.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_B23.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_GB86302I.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_GB86302I.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_RK901.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_RK901.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_RK903.cal:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_RK903.cal \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_RK903.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_RK903.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_RK903_26M.cal:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_RK903_26M.cal \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_WL211.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_WL211.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6212.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6212.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6212a.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6212a.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6214.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6214.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6214a.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6214a.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6216.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6216.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6233f.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6233f.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6236.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6236.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6255.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6255.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6256.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6256.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6275p.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6275p.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6275s.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6275s.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6276p.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6276p.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap62x2.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap62x2.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6354.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6354.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6356.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6356.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6356s.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6356s.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6398s.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6398s.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6398sa.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6398sa.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6398sv.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6398sv.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6452.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6452.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_ap6611s.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_ap6611s.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_awnb108.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_awnb108.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_azw256.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_azw256.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_azw372.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_azw372.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/nvram_cyw88459.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram_cyw88459.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/otp.bin.z77:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/otp.bin.z77 \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/readme.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/readme.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rk903.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rk903.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rk903_26M.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rk903_26M.hcd \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723b_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723b_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723b_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723b_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723bs_VQ0_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723bs_VQ0_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723bs_VQ0_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723bs_VQ0_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723bs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723bs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723bs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723bs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723bu_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723bu_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723d_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723d_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723d_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723d_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723ds_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723ds_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723ds_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723ds_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723f_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723f_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723f_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723f_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723fs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723fs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8723fs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8723fs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8725a_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8725a_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8725a_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8725a_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8725as_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8725as_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8725as_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8725as_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8733b_8723f_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8733b_8723f_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8733b_8723f_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8733b_8723f_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8733b_8723f_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8733b_8723f_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8733bs_8723fs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8733bs_8723fs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8733bs_8723fs_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8733bs_8723fs_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8733bs_8723fs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8733bs_8723fs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761a_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761a_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761a_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761a_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761at8192er_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761at8192er_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761at_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761at_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761at_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761at_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761au8192ee_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761au8192ee_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761au8812ae_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761au8812ae_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761au_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761au_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761aw8192eu_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761aw8192eu_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761aw8192eu_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761aw8192eu_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761b_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761b_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761b_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761b_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761b_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761b_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761bs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761bs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761bt_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761bt_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761bt_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761bt_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8761bt_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8761bt_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821a_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821a_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821a_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821a_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821as_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821as_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821as_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821as_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821c_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821c_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821c_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821c_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821c_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821c_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821cs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821cs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821cs_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821cs_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8821cs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8821cs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822b_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822b_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822b_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822b_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822bs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822bs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822bs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822bs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822c_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822c_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822c_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822c_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822c_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822c_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822cs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822cs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822cs_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822cs_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822cs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822cs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822e_8822c_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822e_8822c_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822e_8822c_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822e_8822c_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822es_8822cs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822es_8822cs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8822es_8822cs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8822es_8822cs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8851bs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8851bs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8851bs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8851bs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8851bu_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8851bu_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8851bu_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8851bu_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852as_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852as_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852as_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852as_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852as_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852as_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852au_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852au_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852au_config_vendor:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852au_config_vendor \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852au_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852au_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852bps_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852bps_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852bps_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852bps_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852bs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852bs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852bs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852bs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852bu_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852bu_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852bu_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852bu_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852cs_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852cs_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852cs_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852cs_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852cu_config:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852cu_config \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/rtl8852cu_fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rtl8852cu_fw \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/ssv6051-sw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ssv6051-sw.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/ssv6051-wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ssv6051-wifi.cfg \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/wifi_efuse_8189e.map:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/wifi_efuse_8189e.map \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/wifi_efuse_8723bs-vq0.map:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/wifi_efuse_8723bs-vq0.map \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/wifi_efuse_8723cs.map:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/wifi_efuse_8723cs.map \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/wifi_efuse_8723ds.map:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/wifi_efuse_8723ds.map \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/firmware/wifi_efuse_8821cs.map:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/wifi_efuse_8821cs.map \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/fstab.rk30board:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.rk30board \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/fstab_swap.ext1024:$(TARGET_COPY_OUT_VENDOR)/etc/fstab_swap.ext1024 \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/fstab_swap.ext2048:$(TARGET_COPY_OUT_VENDOR)/etc/fstab_swap.ext2048 \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/fstab_swap.ext256:$(TARGET_COPY_OUT_VENDOR)/etc/fstab_swap.ext256 \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/fstab_swap.ext4096:$(TARGET_COPY_OUT_VENDOR)/etc/fstab_swap.ext4096 \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/fstab_swap.ext512:$(TARGET_COPY_OUT_VENDOR)/etc/fstab_swap.ext512 \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/fstab_swap.extnone:$(TARGET_COPY_OUT_VENDOR)/etc/fstab_swap.extnone \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/graphic/graphic_profiles.conf:$(TARGET_COPY_OUT_VENDOR)/etc/graphic/graphic_profiles.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.camera.provider-V1-external-service-rk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider-V1-external-service-rk.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.camera.provider-V1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider-V1-service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.optee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.optee.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.graphics.allocator-V1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator-V1-service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.health-service.rockchip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.health-service.rockchip.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.media.c2@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.1-service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.optee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.optee.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.thermal-service.rockchip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal-service.rockchip.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.usb-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb-service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.usb.gadget-service.rockchip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb.gadget-service.rockchip.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/android.hardware.weaver-service.optee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.weaver-service.optee.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hostapd.android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hostapd.android.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/init.box.samba.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.box.samba.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/init.connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.connectivity.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/init.mount_all.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mount_all.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/init.rk30board.environment.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.rk30board.environment.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/init.rk30board.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.rk30board.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/init.rk30board.usb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.rk30board.usb.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/init.rk3576.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.rk3576.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/init.rockchip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.rockchip.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/set_cpu_affinity.sh:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/set_cpu_affinity.sh \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hw/set_performance.sh:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/set_performance.sh \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/hwc3-rk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hwc3-rk.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/init.hdcp2-host.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.hdcp2-host.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/init.rockchip_rkp_factory_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.rockchip_rkp_factory_service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/init.rockchip_udc_detector.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.rockchip_udc_detector.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/init.tee-supplicant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.tee-supplicant.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/init.tune_io.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.tune_io.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/lights-rockchip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lights-rockchip.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/power-aidl-rockchip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/power-aidl-rockchip.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/rk_audio.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rk_audio.service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/rk_bluetooth@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rk_bluetooth@1.0-service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/rk_hdmi.cec-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rk_hdmi.cec-service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/rk_hdmi.connection-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rk_hdmi.connection-service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/rk_wifi.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rk_wifi.service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/rockchip.hardware.outputmanager@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rockchip.hardware.outputmanager@1.0-service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/init/rockchip.hardware.rockit.hw@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rockchip.hardware.rockit.hw@1.0-service.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/pq_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/pq_config.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/pq_setting_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/pq_setting_config.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model0_NaturalSR540to1080_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model0_NaturalSR540to1080_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model0_NaturalSR720to4K_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model0_NaturalSR720to4K_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model0_fd_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model0_fd_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model0_fe_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model0_fe_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model0_fs_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model0_fs_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model0_fsr_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model0_fsr_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model0_sd_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model0_sd_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model0_std_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model0_std_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model1_DC1080p_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model1_DC1080p_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model1_DC540p_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model1_DC540p_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model1_DC720p_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model1_DC720p_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model1_IFBlockX5Stage0_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model1_IFBlockX5Stage0_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model1_IFBlockX5Stage1_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model1_IFBlockX5Stage1_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model1_IFBlockX5Stage2_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model1_IFBlockX5Stage2_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model1_NaturalSR1080to4K_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model1_NaturalSR1080to4K_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model1_fe_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model1_fe_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model2_DC1080p_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model2_DC1080p_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model2_IFBlockX4Stage0_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model2_IFBlockX4Stage0_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model2_IFBlockX4Stage1_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model2_IFBlockX4Stage1_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model2_IFBlockX4Stage2_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model2_IFBlockX4Stage2_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model2_IFBlockX5Stage0_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model2_IFBlockX5Stage0_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model2_IFBlockX5Stage1_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model2_IFBlockX5Stage1_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model2_IFBlockX5Stage2_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model2_IFBlockX5Stage2_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model2_NaturalSR1080to4K_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model2_NaturalSR1080to4K_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model3_IFBlockX4Stage0_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model3_IFBlockX4Stage0_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model3_IFBlockX4Stage1_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model3_IFBlockX4Stage1_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model3_IFBlockX4Stage2_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model3_IFBlockX4Stage2_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model3_IFBlockX5Stage0_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model3_IFBlockX5Stage0_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model3_IFBlockX5Stage1_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model3_IFBlockX5Stage1_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model3_IFBlockX5Stage2_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model3_IFBlockX5Stage2_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model3_NaturalSR1080to4K_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model3_NaturalSR1080to4K_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model3_NaturalSR720to1080_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model3_NaturalSR720to1080_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model4_IFBlockX4Stage0_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model4_IFBlockX4Stage0_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model4_IFBlockX4Stage1_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model4_IFBlockX4Stage1_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model4_IFBlockX4Stage2_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model4_IFBlockX4Stage2_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model4_NaturalSR1080to4K_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model4_NaturalSR1080to4K_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model4_NaturalSR720to1080_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model4_NaturalSR720to1080_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model5_NaturalSR1080to4K_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model5_NaturalSR1080to4K_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rkaipq_mssr_model5_NaturalSR720to1080_rknn200_rk3576.bin:$(TARGET_COPY_OUT_VENDOR)/etc/rkaipq_mssr_model5_NaturalSR720to1080_rknn200_rk3576.bin \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/rockchip_forbid_packages.xml:$(TARGET_COPY_OUT_VENDOR)/etc/rockchip_forbid_packages.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.1-seccomp_policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.1-seccomp_policy \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/seccomp_policy/rockit.vendor.base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/rockit.vendor.base.policy \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/session.xml:$(TARGET_COPY_OUT_VENDOR)/etc/session.xml \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/ueventd.rc \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/vop_base_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/vop_base_config.json \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/wifi/p2p_supplicant_rtk.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_rtk.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/wifi/p2p_supplicant_ssv.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_ssv.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/wifi/wifi.load:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wifi.load \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/wifi/wpa_config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_config.txt \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/etc/wifi/wpa_supplicant_rtk.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_rtk.conf \
    vendor/rockchip/rk3576-common/proprietary/vendor/firmware/fw_rk1608_bypass.rkl:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_rk1608_bypass.rkl \
    vendor/rockchip/rk3576-common/proprietary/vendor/firmware/fw_rk1608_ov2718_1frame.rkl:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_rk1608_ov2718_1frame.rkl \
    vendor/rockchip/rk3576-common/proprietary/vendor/firmware/fw_rk1608_ov2718_2frame.rkl:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_rk1608_ov2718_2frame.rkl \
    vendor/rockchip/rk3576-common/proprietary/vendor/firmware/preisp_imx327.rkl:$(TARGET_COPY_OUT_VENDOR)/firmware/preisp_imx327.rkl \
    vendor/rockchip/rk3576-common/proprietary/vendor/lib/optee_armtz/0b82bae5-0cd0-49a5-9521-516dba9c43ba.ta:$(TARGET_COPY_OUT_VENDOR)/lib/optee_armtz/0b82bae5-0cd0-49a5-9521-516dba9c43ba.ta \
    vendor/rockchip/rk3576-common/proprietary/vendor/lib/optee_armtz/258be795-f9ca-40e6-a869-9ce6886c5d5d.ta:$(TARGET_COPY_OUT_VENDOR)/lib/optee_armtz/258be795-f9ca-40e6-a869-9ce6886c5d5d.ta \
    vendor/rockchip/rk3576-common/proprietary/vendor/lib/optee_armtz/481a57df-aec8-47ad-92f5-eb9fc24f64a6.ta:$(TARGET_COPY_OUT_VENDOR)/lib/optee_armtz/481a57df-aec8-47ad-92f5-eb9fc24f64a6.ta \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/idc/CMIOT_REMOTE.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/CMIOT_REMOTE.idc \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/27330000_pwm.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/27330000_pwm.kl \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/CMIOT_REMOTE.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/CMIOT_REMOTE.kl \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/HiRemote.idc:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/HiRemote.idc \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/HiRemote.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/HiRemote.kl \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/Vendor_0416_Product_0300.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_0416_Product_0300.kl \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/fd8b0030_pwm.idc:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/fd8b0030_pwm.idc \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/fd8b0030_pwm.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/fd8b0030_pwm.kl \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/fe6e0030_pwm.idc:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/fe6e0030_pwm.idc \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/fe6e0030_pwm.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/fe6e0030_pwm.kl \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/fe700030_pwm.idc:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/fe700030_pwm.idc \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/fe700030_pwm.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/fe700030_pwm.kl \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/vendor.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/vendor.kl \
    vendor/rockchip/rk3576-common/proprietary/vendor/usr/keylayout/virtual-remote.idc:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/virtual-remote.idc

PRODUCT_PACKAGES += \
    android.hardware.camera.provider-V1-external-impl-rk \
    arm.graphics-V5-ndk \
    camera.device-external-impl-rk \
    libGLES_mali \
    android.hardware.audio@7.1-impl \
    android.hardware.bluetooth@1.0-impl \
    android.hardware.graphics.allocator-V1-arm \
    android.hardware.graphics.allocator-V1-bifrost \
    android.hardware.graphics.mapper@4.0-impl-bifrost \
    audio.primary.rk30board \
    camera.rk30board \
    hdmi_cec.rk30board \
    hdmi_connection.rk30board \
    hw_output.default \
    hwcomposer.rk30board \
    rockchip.hardware.outputmanager@1.0-impl \
    vulkan.rk3576 \
    libasc_dec \
    libbaseparameter \
    libbt-vendor-aic \
    libbt-vendor-realtek \
    libbt-vendor-seekwave \
    libbt-vendor \
    libcodec2_rk_component \
    libcodec2_rk_store \
    libgpudataproducer \
    libgralloc_priv_omx \
    libhdr_params_parser \
    libhwjpeg \
    libiep \
    libmpp \
    libpq \
    librga \
    librkaiq \
    librkhwpq \
    librkisp \
    librknnrt \
    librkswpq \
    librkwifi-ctrl \
    libsculptor \
    libsync_vendor \
    libteec \
    libtinyalsa_iec958 \
    libvdpp \
    libwifi-hal-aic-rockchip \
    libwifi-hal-bcm-rockchip \
    libwifi-hal-bes-rockchip \
    libwifi-hal-rtk-rockchip \
    libwifi-hal-skw-rockchip \
    libwpa_client \
    rockchip.hardware.outputmanager@1.0 \
    libanr \
    librockit_hw_hidl@1.0 \
    rockchip.hardware.rockit.hw@1.0 \
    camera.device-internal-impl-rk \
    libRkTeeGatekeeper \
    libRkTeeKeymaster \
    libRkTeeWeaver \
    libRkWeaver \
    libRkcppcose_rkp \
    libRkgatekeeper \
    libRkkeymaster4 \
    libRkkeymaster_messages \
    libRkkeymaster_portable \
    libRkkeymint \
    libRkpuresoftkeymasterdevice \
    libRksoft_attestation_cert \
    libRksoftkeymasterdevice \
    lib_Rk_keymaster_keymint_utils \
    libcppbor_external_rk \
    libvendor_storage \
    libwifi-hal \
    android.hardware.camera.provider-V1-external-service.xml \
    android.hardware.camera.provider-V1-service.xml \
    android.hardware.gatekeeper-service.optee.xml \
    android.hardware.health-service.rockchip.xml \
    android.hardware.security.keymint-service.optee.xml \
    android.hardware.security.secureclock-service.optee.xml \
    android.hardware.security.sharedsecret-service.optee.xml \
    android.hardware.thermal-service.rockchip.xml \
    android.hardware.usb-service.xml \
    android.hardware.usb.gadget-service.rockchip.xml \
    android.hardware.weaver-service.optee.xml \
    hwc3-default.xml \
    lights-rockchip.xml \
    manifest_allocator.xml \
    manifest_media_c2_V1_1.xml \
    power-aidl-rockchip.xml \
    rk_hdmi.cec.xml \
    rk_hdmi.connection.xml \
    rk_wifi.hostapd.xml \
    rk_wifi.service.xml \
    rk_wifi.supplicant.xml \
    rockchip.hardware.outputmanager@1.0-service.xml \
    rockchip.hardware.rockit.hw@1.0-service.xml \
    flash_img \
    gpu_counter_producer-rockchip \
    hdcp2_tx_rx \
    android.hardware.audio.service \
    android.hardware.bluetooth@1.0-service \
    android.hardware.camera.provider-V1-external-service-rk \
    android.hardware.camera.provider-V1-service \
    android.hardware.gatekeeper-service.optee \
    android.hardware.graphics.allocator-V1-service \
    android.hardware.graphics.composer3-service.rockchip \
    android.hardware.health-service.rockchip \
    android.hardware.lights-service.rockchip \
    android.hardware.media.c2@1.1-service \
    android.hardware.power-service.rockchip \
    android.hardware.security.keymint-service.optee \
    android.hardware.thermal-service.rockchip \
    android.hardware.tv.hdmi.cec-service \
    android.hardware.tv.hdmi.connection-service \
    android.hardware.usb-service.rockchip \
    android.hardware.usb.gadget-service.rockchip \
    android.hardware.weaver-service.optee \
    android.hardware.wifi-service \
    hostapd-rockchip \
    rockchip.hardware.outputmanager@1.0-service \
    rockchip.hardware.rockit.hw@1.0-service \
    wpa_supplicant \
    init.insmod \
    media-ctl \
    preinstall \
    preinstall.sh.bak \
    read_pcie_info \
    rk_vendor_storage_tool \
    rkauth_tool_bin \
    rkauth_verify_licence \
    rkdevice_info \
    rkhelper \
    rkpq_tool_server \
    rkswpq_demo \
    rockchip_rkp_factory_extraction_tool \
    rockchip_udc_detector \
    tee-supplicant \
    v4l2-ctl
